name = "power"
name_pretty = "Power"
icon = "shutdown"
global_search = true

[[entries]]
text = "Logout"
icon = "logout"
keyword = ["logout", "log out", "signout"]
actions = { "logout" = "pkill -f niri && pkill -f sway" }

[[entries]]
text = "Suspend"
icon = "suspend"
keyword = ["suspend", "sleep", "hibernate"]
actions = { "suspend" = "systemctl suspend" }

[[entries]]
text = "Reboot"
icon = "reboot"
keyword = ["reboot", "restart"]
actions = { "reboot" = "systemctl reboot" }

[[entries]]
text = "Shutdown"
icon = "shutdown"
keyword = ["shutdown", "power off", "turn off"]
actions = { "poweroff" = "systemctl poweroff" }
