gui:
  theme:
    activeBorderColor:
      - "#8ec07c"
      - bold
    inactiveBorderColor:
      - "#a89984"
    optionsTextColor:
      - "#83a598"
    selectedLineBgColor:
      - "#504945"
    cherryPickedCommitBgColor:
      - "#3c3836"
    cherryPickedCommitFgColor:
      - "#8ec07c"
    unstagedChangesColor:
      - "#fb4934"
    defaultFgColor:
      - "#ebdbb2"
    searchingActiveBorderColor:
      - "#fabd2f"
  authorColors:
    "*": "#83a598"
  border: "single"
disableStartupPopups: true
