gui:
  theme:
    activeBorderColor:
      - "#88c0d0"
      - bold
    inactiveBorderColor:
      - "#4c566a"
    optionsTextColor:
      - "#81a1c1"
    selectedLineBgColor:
      - "#3b4252"
    cherryPickedCommitBgColor:
      - "#434c5e"
    cherryPickedCommitFgColor:
      - "#88c0d0"
    unstagedChangesColor:
      - "#bf616a"
    defaultFgColor:
      - "#eceff4"
    searchingActiveBorderColor:
      - "#ebcb8b"
  authorColors:
    "*": "#88c0d0"
  border: "single"
disableStartupPopups: true
