[styles.tables]
headers = { color = "#ebdbb2" }

[styles.cpu]
all_entry_color = "#ebdbb2"
avg_entry_color = "#fb4934"
cpu_core_colors = [
  "#fb4934",
  "#fe8019",
  "#fabd2f",
  "#b8bb26",
  "#83a598",
  "#8ec07c",
]

[styles.memory]
ram_color = "#b8bb26"
swap_color = "#fe8019"
gpu_colors = ["#8ec07c", "#d3869b", "#fb4934", "#fe8019", "#fabd2f", "#b8bb26"]
arc_color = "#83a598"

[styles.network]
rx_color = "#b8bb26"
tx_color = "#fb4934"

[styles.widgets]
widget_title = { color = "#ebdbb2" }
border_color = "#504945"
selected_border_color = "#8ec07c"
text = { color = "#ebdbb2" }
selected_text = { color = "#282828", bg_color = "#8ec07c" }

[styles.graphs]
graph_color = "#a89984"

[styles.battery]
high_battery_color = "#b8bb26"
medium_battery_color = "#fabd2f"
low_battery_color = "#fb4934"
